### ISSUE TITLE
Get features for each line

### ISSUE THREAD

**Issue by IKetchup** [fraunhoferportugal/tsfel#114]
Hello,

I would like to generate features for each observation of my time serie and not only window by window.

Does this possibility exist in tsfel and do you know how to do it ?

Thanks in advance

**Comment by dmfolgado** [comment]
Hello, if you're interested in extracting features for each observation you must set the `window_size=1`. An example code would be:

```python
import tsfel

ts = np.random.randn(100)
cfg = tsfel.get_features_by_domain("statistical")
features = tsfel.time_series_features_extractor(cfg, ts, window_size = 1, fs=100)
print(len(ts), np.shape(features))

```
You should have `100` lines in the feature vector (one line per observation of your time series of `len=100`).

Please note that for some features it is not adequate to use a feature per observation since they are expecting a window larger than 1.  The values calculated values should be carefully interpreted and you are recommended to select features that make sense calculating with individual observations. You might also encounter some errors in spectral features that are expecting a larger window size.
