### ISSUE TITLE
Error in TSFEL_HAR_Example.ipynb

### ISSUE THREAD

**Issue by snowbbbb** [fraunhoferportugal/tsfel#140]
Hi, thank you for your contribution of so useful package. I run the template code TSFEL_HAR_Example.ipynb. However I find the feature dimension of X_train is (1,49792), and it raises error "ValueError: No feature in X meets the variance threshold 0.00000 (X contains only one sample)". So do I need to reshape the feature? And are returned features of many time series ordered or unordered?(I try it, but find it unordered)

**Comment by mbarandas** [comment]
Hi @snowbbbb,
Thank you for using TSFEL and for bringing attention to this issue. 
In the latest release, we made changes to the allowed input formats, but we forgot to update the notebook. @time_series_feature_extractor function allows different input formats. Lists are used when the input signal is already split into windows, which is the case for the HAR dataset. Otherwise, if the input is an array, it is assumed that each column represents a signal channel and not a window.

The issue has already been fixed in the notebook.
