### ISSUE TITLE
Can we add the correlation of different channels for the multivariate time series?

### ISSUE THREAD

**Issue by KarenMars** [fraunhoferportugal/tsfel#172]
Hi,

I am curious about whether the correlation of different channels for multivariate time series can be added as a feature. Actually, I have seen most of the auto feature extraction tools, such as tsfresh, do not include features for caputuring the relationship between different channels. I wonder why they are not included.

**Comment by dmfolgado** [comment]
Hi @KarenMars! Thank you for your suggestion. I can see at least two considerations about implementing this feature that might explain why most libraries are not providing cross-dimension (cross-channel) relationships by design.

**Design simplicity assumptions.** Cross-channel features complicate the preprocessing pipeline, as correlation computations rely on having data from multiple dimensions (channels) available and synchronized.

**Increased computational complexity.** If the number of dimensions (channels) grows, the number of possible pairwise correlations grows quadratically, which could become infeasible for large time series datasets.

A high-quality package I highly recommend is [pyspi](https://github.com/DynamicsAndNeuralSystems/pyspi). You could potentially combine the outputs of both TSFEL and Pyspi to leverage their strengths and maximize their utility.

**Comment by KarenMars** [comment]
Thank you very much for the reply, I'm totally agree with the complexity brought by these features related to correlation. Also, your  recommendation of pyspi is quite useful, I will check it out : )
