### ISSUE TITLE
How to use this library with a timeseries dataframe ?

### ISSUE THREAD

**Issue by alvinhenrick** [fraunhoferportugal/tsfel#56]
Would you be able to share an example ? How to use this library with a timeseries dataframe?

Library is great it is just that, I am trying to get my head around `fs` and `window_size` parameter to feed my hourly data .

Basically how I can do i have to map the data from time to frequency ?

My schema looks looks like this one below : 
hourly recording :
id, time, feature1, feature2 , target

Thanks!

**Comment by dmfolgado** [comment]
Hi Alvin,

We do appreciate your feedback! As of today, we do not support directly timeseries dataframes. Nevertheless, due to the number of recent requests, we added to our development roadmap.

Nevertheless, you should be able to use TSFEL with some workarounds in the data structure. Pass the input as a NumPy array only with the input data [feature1, feature2], the appropriate sampling rate and window size. 

The `fs` parameter should be the sampling rate. For hourly data use `fs = 1/3600`. Regarding the win_size you should pass the window size in the number of samples. If the window_size it's 5 days for instance, then  `window_size = 5` (5 x 3600 x 1/3600).
Please refer to [this ](https://github.com/fraunhoferportugal/tsfel/issues/33)closed issue that was related to timeseries dataframes also.

Let us know if you run into any more issues and we can help.

**Comment by alvinhenrick** [comment]
@dmfolgado Thank you for the quick response. I was able to workaround the issue the way you suggested. I also had to set `window_spliter=True`. 
We can close the issue.
