### ISSUE TITLE
Detailed handbook for users or GUI?

### ISSUE THREAD

**Issue by IrenXu** [fraunhoferportugal/tsfel#73]
Hi,

I am wondering if there is a gui version of tsfel.
Also, what should the input data look like? Is this able to compute multiple timeseries at the same time and extract their features and cluster them based on the features?

**Comment by mbarandas** [comment]
Hi. TSFEL does not have a GUI version. However we developed a frontend using Google Sheets API where you can use an online spreadsheet to choose the desired feature extraction methods. 
A tutorial with an illustrative example which uses an online spreadsheet to configure TSFEL is available on a [Google Colab](https://colab.research.google.com/github/fraunhoferportugal/tsfel/blob/development/notebooks/TSFEL_HAR_Example.ipynb)

Regarding the computation of multiple timeseries at the same time I recommend that you use `dataset_features_extractor`. We are still updating the documentation of this method. However you have a small example [here](https://tsfel.readthedocs.io/en/latest/descriptions/get_started.html#extract-from-time-series-stored-in-datasets) and you can also read _Section 2.2.1. Data ingestion and preprocessing_ of [TSFEL publication](https://www.sciencedirect.com/science/article/pii/S2352711020300017) which addresses that topic.

**Comment by IrenXu** [comment]
Hi,
Thank you very much!
I could use TSFEL in notebook now, still there are some questions.
1. when i export all the features, there seem to be 390 features, i took a look, it seems that several features had several sub-features of their own, like wavelet_variance1/2/3 etc. how come?
2. then i tried to extract certain features, so i downloaded the googlespreadsheet on the website, yet it says this:
![image](https://user-images.githubusercontent.com/77282283/105646121-ff391080-5e95-11eb-8dbb-46214f395891.png)
So how should I extract features that I want? what format should the spreadsheet be in?

Many thanks!

**Comment by mbarandas** [comment]
Hi,
1. There are features that returns more than one feature due to their meaning. For example, the `wavelet_var` computes the CWT variance value of each wavelet scale where the widths use for the transformation is given by a default value. Therefore, the number of `wavelet_var` sub features is given by its number of widths. From the `feature_extraction\features.json` file you can check the `n_features` key to understand the expected number of sub features a given feature will return. We also have a `get_number_features` method that returns the number of features that will be returned from your configuration file.

2. TSFEL has different methods to create the configuration file for the feature extraction. If you would like to use the `extract_sheet` method the google spreedsheet needs to be online and shared with TSFEL e-mail: featext@featext.iam.gserviceaccount.com (as explained in google colab example). If this option is not suitable for you you can also use one of the following options:

```python
cfg = tsfel.get_features_by_domain()  # All available features

cfg = tsfel.get_features_by_domain(domain='temporal')  # Only temporal features. Available domains: statistical, temporal, spectral

cfg = tsfel.load_json('your_json_file_path')  # Features from your json file

```
For the `load_json` method you can download [feature_extraction\features.json](https://github.com/fraunhoferportugal/tsfel/blob/development/tsfel/feature_extraction/features.json) and set the `use` key (values: 'yes' or 'no') according to your preferences.

**Comment by IrenXu** [comment]
Hi,

Thank you so much for your explanation!
