### ISSUE TITLE
Question: Comparison tsfel and tsfresh

### ISSUE THREAD

**Issue by nils-braun** [fraunhoferportugal/tsfel#76]
Hi tsfel developers!
Nice package! Congratulations on this. 
I am one of the authors of [tsfresh](https://tsfresh.readthedocs.io/en/latest/). I would be very much interested in understanding if there is something we can learn from each other? Is there a functionality tsfresh could provide to tsfel? Or the other way round? Would you even think it makes sense to combine efforts?
Happy to hear your opinion :-)

**Comment by dmfolgado** [comment]
I do really appreciate your kind words regarding TSFEL. Coming from the development team of TSFRESH is even more rewarding to us since your library inspired us in the early stages of the TSFEL development.

We are open to collaborate with you to exchange functionalities between both libraries. Perhaps the most effective way would be setting up a short meeting to know each other and exchange some ideas. Would you also think it would be a good idea?

**Comment by pjbhaumik** [comment]
Hi, TSFRESH offers the ability to rate the relevance of the extracted features. Will TSFEL do the same?

**Comment by dmfolgado** [comment]
Hi! At the moment we're not considering it in our short-term roadmap since it opens a variety of problem-related assumptions and methods to address the feature importance topic.
