### ISSUE TITLE
How to extract certain feats from a domain

### ISSUE THREAD

**Issue by saydeking** [fraunhoferportugal/tsfel#99]
Hi, thanks for this tool! It's a huge help. I'm struggling with how I go about extracting some but not all features from the spectral domain.

To extract all we use something like this: 
cfg_file = tsfel.get_features_by_domain('spectral')
data = tsfel.time_series_features_extractor(cfg_file, data, fs=fs)

Which function can we use to extract a list of chosen features?
Thanks!

**Comment by mbarandas** [comment]
Hi! Thanks for your interest in our package.

Instead of `cfg_file = tsfel.get_features_by_domain('spectral')` you can use `cfg_file = tsfel.load_json(your_json_file_path)`

You can download [feature_extraction\features.json](https://github.com/fraunhoferportugal/tsfel/blob/development/tsfel/feature_extraction/features.json) and set the `use` key (values: 'yes' or 'no') according to your preferences.

**Comment by saydeking** [comment]
Awesome! I'll give this a go, thank you so much for your swift response.

**Comment by espjose** [comment]
hola deseo extraer solo algunas caracteristicas en el dominio, pero no entiendo como hacerlo me podria explicar mas detalladamiente por favor 
features_TEST_H_a2 = tsfel.time_series_features_extractor(tsfel.get_features_by_domain('statistical'),D_test_h["a2"], fs=30, window_size=703)
features_TEST_H_a2

**Comment by mbarandas** [comment]
Hi @espjose!

In your example you are extracting statistical features and it seems to be correct.
Can you elaborate on your issue please?
